services:

  bookanything-infra-kafka-broker:
    image: confluentinc/cp-kafka:7.6.0
    hostname: ${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-kafka-broker
    container_name: ${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-kafka-broker
    environment:
      # - ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_LISTENERS=LISTENER_INT://${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-kafka-broker:9092,LISTENER_EXT://localhost:29092
      # - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_EXT
      # - KAFKA_ADVERTISED_LISTENERS=LISTENER_INT://${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-kafka-broker:9092,LISTENER_EXT://localhost:29092
      # - KAFKA_ADVERTISED_HOST_NAME=${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-kafka-broker
      # - PLAINTEXT://${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-kafka-broker:9092,
      # - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_MESSAGE_MAX_BYTES=52428800
      - KAFKA_REPLICA_FETCH_MAX_BYTES=52428800
      - KAFKA_LOG4J_ROOT_LOGLEVEL=ERROR
      - KAFKA_LOG4J_LOGGERS=org.apache.zookeeper=ERROR,org.apache.kafka=ERROR,kafka=ERROR,kafka.cluster=ERROR,kafka.controller=ERROR,kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - LANG=en_US.utf8
      - LC_ALL=en_US.utf8
      - JDK_JAVA_OPTIONS=-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
    ports:
      - "9092:9092"
      - "29092:29092"
    expose:
      - "9092"
      - "29092"
    # healthcheck:
    #   test: kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    depends_on:
      bookanything-infra-zookeeper:
        condition: service_started
    volumes:
      - kafka-data-volume-01:/var/lib/kafka/data
    networks:
      bookanything-network-dev1-01:
        ipv4_address: 172.100.0.20


  bookanything-infra-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: ${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-zookeeper
    container_name: ${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
        - "2181:2181"
        - "21810:8080"
    expose:
      - "2181"
      - "8080"
    # healthcheck:
    #   test: ["CMD-SHELL", "echo ruok | nc -w 2 zookeeper 2181 | grep imok || exit 1"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 3
    volumes:
      - zookeeper-data-volume-01:/var/lib/zookeeper/data
      - zookeeper-logs-volume-01:/var/lib/zookeeper/log
    networks:
      bookanything-network-dev1-01:
        ipv4_address: 172.100.0.21


  bookanything-utils-kafka-admin-ui:
    image: provectuslabs/kafka-ui:v0.7.1
    hostname: ${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-utils-kafka-admin-ui
    container_name: ${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-utils-kafka-admin-ui
    ports:
      - "8092:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-kafka-broker:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-zookeeper:2181
    expose:
      - "8080"
      - "8092"
    links:
      - ${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-kafka-broker:${ENV_DEFAULT_DOCKERCNTR_NAME_PREFIX}-infra-kafka-broker
    networks:
      bookanything-network-dev1-01:
        ipv4_address: 172.100.0.22


volumes:
  zookeeper-logs-volume-01:
    driver: local
  zookeeper-data-volume-01:
    driver: local
  kafka-data-volume-01:
    driver: local

